-- NO-OP (kept intentionally): the original config:* -> configs:* permission alignment
-- has been moved to V13__align_configs_permission_naming.sql.
-- Reason: V4 runs before V8 creates app_permission/app_role_permission, so executing
-- RBAC-dependent SQL at V4 can fail on empty-database initialization.
